### PR TITLE
15 goldfish fails to peek

### LINKED ISSUE #15: Goldfish fails to peek
Goldfish often gives this error:
`goldfish: unable to handle request from [ADDRESS] failed to read message from connection: failed to peek into message: EOF
`

The cause is currently unknown, but it may have something to do with the amount of incoming requests it has to parse.

### PR DESCRIPTION
**Pull request by kevba**
Closes #15

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -57,6 +57,9 @@ func (s *Server) handleConn(conn io.ReadWriteCloser) error {
 	for {
 		buf, err := s.readMessage(r)
 		if err != nil {
+			if err == io.EOF {
```
Comment (OrangeTux) [inline server.go]: Could you add a comment explaining why you do this?

File: example/main.go [hunk 2]
```diff
@@ -40,6 +41,7 @@ func handleReadCoils(unitID, start, quantity int) ([]modbus.Value, error) {
 // [31, 298, 1999].
 func handleRegisters(unitID, start, quantity int) ([]modbus.Value, error) {
 	registers := make([]modbus.Value, quantity)
+	fmt.Printf("%v", start)
```
Comment (OrangeTux) [inline example/main.go]: I think you accidentally commit some changes.

File: example/main.go [hunk 3]
```diff
@@ -48,7 +50,7 @@ func handleRegisters(unitID, start, quantity int) ([]modbus.Value, error) {
 
 		registers[i] = v
 	}
-
+	time.Sleep(1 * time.Second)
```
Comment (OrangeTux) [inline example/main.go]: I think you accidentally commit some changes.

File: example/main.go [hunk 4]
```diff
@@ -68,7 +70,7 @@ func handleWriteCoils(unitID, start int, values []modbus.Value) error {
 }
 
 func main() {
-	addr := flag.String("addr", ":502", "address to listen on.")
+	addr := flag.String("addr", ":5020", "address to listen on.")
```
Comment (OrangeTux) [inline example/main.go]: I think you accidentally commit some changes.

**Review by OrangeTux — CHANGES_REQUESTED** [review]
Coudl you also merge the 2 commits into a 1 commit?

```
$ git rebase -i $(git merge-base $(git branch | sed -n '/\* /s///p') master)
```
Than you can force push this new commit.
